version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_WS_URL=ws://backend:4000
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/packages/frontend/.next
    networks:
      - carbon-net

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/carbon-impact
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-here
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
      - backend-data:/app/data
    depends_on:
      - mongo
      - redis
    privileged: true
    networks:
      - carbon-net

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - carbon-net

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - carbon-net

networks:
  carbon-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  backend-data: